### PR TITLE
Add support for submitting Python 2/3 compatible add-on to matrix branch

### PR DESCRIPTION
**Pull request by mediaminister**

### CODE REVIEW

**Comment by enen92** [comment]
I don't really like the solution but looks like it was @romanvm decision (and it's his project anyway) so I'm fine with it since it's a valid options.

Can you bump the action version?

Thanks

**Comment by mediaminister** [comment]
In the README.md? Which version should I choose? v1.1?

**Comment by enen92** [comment]
Nevermind, I forgot action versioning is achieved when you tag a release. But yes please change in readme and I'll tag it after merging. Don't forget to update your action definition in your projects

**Comment by enen92** [comment]
Also @mediaminister README needs an entry for the new `input`

**Comment by mediaminister** [comment]
Okay, I think everything is added as it should be.

**Comment by enen92** [comment]
thanks a lot

**Pull request merged**
